using System.Text;

namespace Infrastructure.Storage.Fake;

public class FakeStorageManager : IFileStorageManager
{

    public string GenerateSignedUrl(IFileEntry fileEntry)
    {
        return $"https://fake-storage.com/{fileEntry.FileLocation}";
    }

    public Task CreateAsync(IFileEntry fileEntry, Stream stream, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }

    public Task CreateAsync(IFileEntry fileEntry, Stream stream, string contentType, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }

    public Task DeleteAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }

    public Task<byte[]> ReadAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.FromResult(Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager."));
    }

    public Task DownloadAsync(IFileEntry fileEntry, Stream stream, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }

    public Task<Stream> DownloadAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.FromResult<Stream>(new MemoryStream(Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager.")));
    }

    public void Dispose()
    {
    }
}
